# Generated by Django 5.1.7 on 2025-03-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avatar_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avataruser',
            options={'ordering': ('pk',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
