# Generated by Django 5.1.7 on 2025-03-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avataruser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatars/'),
        ),
    ]
