# Generated by Django 5.1.7 on 2025-03-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar_user', '0002_alter_avataruser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avataruser',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='avatars/'),
        ),
    ]
