# Generated by Django 5.1.7 on 2025-03-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avatar_user', '0003_alter_avataruser_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avataruser',
            old_name='image',
            new_name='avatar',
        ),
    ]
