volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram-db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: foodgram-back
    image: aiukan/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/collected_static/
      - media:/app/media
  frontend:
    container_name: foodgram-front
    env_file: .env
    image: aiukan/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    container_name: foodgram-proxy
    image: aiukan/foodgram_gateway
    env_file: .env
    ports:
      - 9000:80
    depends_on:
      - frontend
      - backend
    volumes:
      - static:/staticfiles
      - media:/media