volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram-db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: foodgram-back
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/collected_static/
      - media:/app/media
  frontend:
    container_name: foodgram-front
    env_file: .env
    build: ./frontend/
    volumes:
      - static:/app/result_build/build
  nginx:
    container_name: foodgram-proxy
    build: ./infra/
    env_file: .env
    ports:
      - "9000:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - static:/usr/share/nginx/html/
      - media:/media
      - ./docs/:/usr/share/nginx/html/api/docs/